# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

name: "fake_embedder"
backend: "python"
max_batch_size: 4

input [
  {
    name: "TEXT"
    data_type: TYPE_STRING
    dims: [ 1 ]
  }
]

output [
  {
    name: "EMBEDDING"
    data_type: TYPE_FP32
    dims: [ 8 ]
  }
]

instance_group [
  { kind: KIND_CPU }
]
